### ISSUE TITLE
TwitchApi.GetSubscriberCount: Current sub count: System.Threading.Tasks.Task`1[System.Int32] #

### ISSUE THREAD

**Issue by JustMeDaFaq** [swiftyspiffy/TwitchLib#102]
Its me again - sorry :D

When calling TwitchApi.GetSubscriberCount in the example, im just getting

Current sub count: System.Threading.Tasks.Task`1[System.Int32] 

In the Messagebox. Using this with an non partnered account. Does it work with partnered account correctly? Could we may just get 0 subscriber if non partnered/request didnt suceed?

**Comment by swiftyspiffy** [comment]
So since this is an asynchronous call, you'll need to either await the call or use the .Result property (not recommended due to possible race conditions). The example application shows how to await a call.
https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLibExample/TwitchLibExample/Form1.cs#L355

Exception it'd be like:
```
int count = await TwitchApi.GetSubcriberCount("channel");
```

I'm actually not sure what is returned for a non-partnered streamer, never tried. Maybe you're able to see? I suspect it'll probably throw an exception?

**Comment by JustMeDaFaq** [comment]
Original Exception:
Eine Ausnahme vom Typ "System.Net.WebException" ist in mscorlib.dll aufgetreten, doch wurde diese im Benutzercode nicht verarbeitet.

Zusätzliche Informationen: Der Remoteserver hat einen Fehler zurückgegeben: (422) Unprocessable Entity.

**Comment by swiftyspiffy** [comment]
If it 422's, it can definitely be caught. Will look into it now.

**Comment by JustMeDaFaq** [comment]
Thanks for all your help. Just got back home, its around 5 o clock over here. Happy new year! Gonna be probably as hard as 2016 was, tho, fighting for your goald will be worth it :)
