### ISSUE TITLE
Names of things changed in newer version

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#134]
Hi there, this is my first c# project that depends on an external library so please excuse me if I am using it incorrectly but I notice that almost every time I update the Twitchlib package in Nuget the names of things change and then I have to try and figure out where they went.

For example this morning I upgraded to the latest version and now things like this no longer resolve in visual studio:

TwitchApi.BroadcasterOnline
TwitchApi.GetTwitchChannel
TwitchApi.GetUser

I also noticed that I had to add these definitions to the top of my project in order to find some of the models:

using TwitchLib.Models.API.Follow;
using TwitchLib.Models.API.User;
using TwitchLib.Models.API.Channel;

Am I writing my code incorrectly or defining things in a way that is causing my project to break whenever I update or is it that things are being moved around a lot inside of Twitchlib currently?

an example is:

 bool online = await TwitchApi.BroadcasterOnline(channelName);

Also I had a question would it be possible to leave IRC support as an option since the library you are using for websockets is in like pre-alpha alpha?

thanks for all of your hard work.

**Comment by swiftyspiffy** [comment]
Hi zerocarbthirty. This is actually my first relatively popular library. I've been reading up and learning a ton about proper structure of libraries by looking at various other popular libraries. As a result, I've been refining the structure of the library to be more user friendly and consistent with .net library layouts. So, to that point, yes the structure has been changing, and I'm sorry about that. I figure for the long run, its best to get the growing pains out at the start.
Regarding the websocket library, this is another tricky one. So websocket sharp is released with the suffix "Rc" in the version meaning release candidate. NuGet package manager looks at any version with letters in it as a prerelease. This means that even though the developer flagged his library as a "release candidate" NuGet flags it as a "prerelease". Because of this, I have uploaded my own build of websocketsharp with "NonPreRelease" in its name. This allowed me to reference it in TwitchLib without forcing TwitchLib to be flagged as prerelease.

Hopefully that clears it up a bit.

**Comment by zerocarbthirty** [comment]
Can you tell me if it would be possible to pick between irc and sockets?

**Comment by swiftyspiffy** [comment]
No, it is not possible to pick one or the other. For that to be possible, we'd need to package in code for IRC or include a dependency to make it possible, which I feel would bloat the project even more than it is bloated at the moment.

Part of the reason we moved over from IRC was because we caught word that some Twitch functionality may be migrating off of IRC in favor of websockets in the near future, mainly whispers. If there's enough interest for the ability toggle between IRC and websockets, I guess we could provide both, but it seems like extra bloat for little gain.

It is also important to point out that I believe websockets will be quite a bit faster and more efficient once the parsing in the project is redone. The reason for this is that the websocket implementation sends sends many pieces of information in a single transmission, rather than then IRC implementation which sends a single piece of information per message. However, the parsing is currently transforming the websocket messages into individual messages for parsing, which I think eliminates any kind of speed increase we'd see from websockets.

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this. Feel free to reopen as necessary :)
