### ISSUE TITLE
Using OnViewerJoined breaks OnMessageRecieved

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#14]
Hello again!

Using OnViewerJoined event is causing TwitchChatClient to stop firing OnMessageRecieved. And, OnViewerJoined (if I've got it's purpose right) breaks too - event fires once on my bot (that's using your lib) and then doesn't fires on me joined to the chat room. Commenting line
`chat.OnViewerJoined += Chat_OnViewerJoined;`
fixes this, but I need OnViewerJoined working :(

Thanks

**Comment by swiftyspiffy** [comment]
I'll look into this, and have a fix for this, the resub notifications, and UTF8 API calls going out tonight.

Thanks.

**Comment by swiftyspiffy** [comment]
So I've been unable to reproduce this.  It may be because the work I have done coincidentally fixed it, not sure.  I have added a function called 'testOnReadLine'.  You can pass in an IRC string  (for example, a join: :felixfressack!felixfressack@felixfressack.tmi.twitch.tv JOIN #burkeblack).  You can get the IRC strings by initializing the library in logging mode (when initializing a chat/whisper client, set [bool logging = false] to true, this will cause the library to print entire IRC strings to the console). When passing an IRC string to testOnReadLine, set a break point, and see if there is some sort of crash going on that is being suppressed, but causing functionality to break.

**Comment by swiftyspiffy** [comment]
As a side note, releasing a new NuGet version now, give that a try and let me know if you still have the aforementioned issue.

**Comment by igor523** [comment]
It's sad, that you've been unable to reproduce this. I can show you this bug in video tommorow, if you wish.
Regarding of new version: thanks, I'll try it later.

P.S. Sorry if my English contains some grammar mistakes

**Comment by swiftyspiffy** [comment]
No worries, it's all good.  Try putting a breakpoint when calling testOnReadLine and pass in a JOIN twitch IRC message, and see if any exceptions are thrown in the process (this is what would cause the library to essentially shut down).

Sorry for not being able to reproduce.

**Comment by igor523** [comment]
Well, looks like it's trouble on my end. Something related with events, calling event in event handler suddenly breaks all... But this is my troubles for now. Sorry for false alert.
