### ISSUE TITLE
Watch for channel to go live

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#144]
Is it possible to fire an event when a channel goes live? I scoured the API docs and it doesn't seem there's any message for it, which would explain why there's no event for it. Does something else happen in chat when the channel goes live?

I'd love to do a pull request to add an event for this if it's somehow possible, but if the Twitch API doesn't send it then nothing can be done.

**Comment by swiftyspiffy** [comment]
There are a few ways to do this, I think. The first, which might be most "documented" by Twitch and most straight forward would be to simply poll the /streams endpoint. This could be a service in TwitchLib similar to the FollowerService. The FollowerService simply polls the Twitch API on a set interval and then fires an event when it notices a difference. The same could be done for something like a StreamStatusService or something. This service could pull the Twitch API and fire an event when it noticed the stream endpoint returns offline or online.

If you'd like to give it a stab, I'm more than open to it. I can even merge and modify it if I see something that could be better.

The other route, which is not documented at the moment, is through a PubSub topic. I wouldn't recommend this not only because it requires a new connection be established (using PubSubClient) but also because of it being undocumented meaning Twitch can change it without saying anything at anytime.

Cheers

**Comment by elu00** [comment]
If neither you nor vaindil are interested in picking this up, I'll try to have a PR for this within the week. 😄

**Comment by swiftyspiffy** [comment]
I'll be able to do it in about a week and a half. If you want to take a stab, you're more than welcome to. Might I suggest kind of following the FollowerService format, and using a built in library function to check if the stream is live, perhaps `TwitchApi.Streams.BroadcasterOnline(string channel)`.

Thanks in advance :)

**Comment by vaindil** [comment]
@elu00 I have no problem with it. Up to you, let me know if you want to or if you want me to.

**Comment by vaindil** [comment]
Another thought I just had--this won't cause an issue with rate limits, will it? I don't imagine the limits are so low that this would be a problem, just wanted to check. I'm not familiar with that as I've never written anything heavy enough to need to monitor it.

**Comment by elu00** [comment]
Hiya,
I've implemented basic functionality for this event through a new service (LiveChannelMonitor).
[Here](https://github.com/elu00/TwitchLib/commit/378fe8895b38f9e14f1bb7a1360992b0d4c6e9b3)'s my commit for what I've done so far; feel free to look over it to check if there's anything particularly troubling.
However, my implementation is kind of awkward in that it's constructor requires a `List<JoinedChannels>`, which probably only can be called from a TwitchClient, so I'll be refactoring that before sending in a PR.
Thanks!

**Comment by swiftyspiffy** [comment]
Looks good, just a couple recommendations I'd make:
- Modify the namespace in each of the events from TwitchLib.Events.Services.FollowerService to TwitchLib.Events.Services.LiveChannelMonitor
- Kind of nitpicky, but I would change the name from LiveChannelMonitor to LiveStreamMonitor, since the Twitch API differentiates the two (channel objects always exist (unless user is banned or something) and stream objects only exist while the stream is active.
- I think the ClientId value should be accessible from TwitchAPI, that way we're always sourcing this value from the same place. (it looks like this needs to be applied to FollowerService as well).
- As you mentioned, we probably want to pass in a list of strings that represent the channels/streams to watch.
- Additionally, we also might want to accept a list of strings representing channel/user IDs as an overloaded constructor so that we account for the move from usernames -> user id's.
- Another nitpicky thing, perhaps move the #Events region to at the top so that someone viewing the code would immediately know the events to subscribe to.

Other than that, looks good. Thanks a ton :)

**Comment by swiftyspiffy** [comment]
I'll cross post over to the pull request to.

**Comment by swiftyspiffy** [comment]
I will go ahead and close this based on #146 :)

Thanks!
