### ISSUE TITLE
Support for use in UWP Apps

### ISSUE THREAD

**Issue by TheBekker** [swiftyspiffy/TwitchLib#147]
Would love to be able to use this for the more modern UWP Apps.

Currently nuget install gives follwing error when used on UWP app:
`install-package : Package TwitchLib 1.4.3 is not compatible with uap10.0 (UAP,Version=v10.0). Package TwitchLib 1.4.3 supports: net45 (.NETFramework,Version=v4.5)`
 
`install-package : Package WebSocketSharp-NonPreRelease 1.0.0 is not compatible with uap10.0 (UAP,Version=v10.0). Package WebSocketSharp-NonPreRelease 1.0.0 supports: net35 (.NETFramework,Version=v3.5)`

**Comment by swiftyspiffy** [comment]
Sorry about the delay ok this. I was not aware of this. What are the requirements to make this compatible with UWP Apps? Sorry I'm pretty new to it.

**Comment by TheBekker** [comment]
I'm not entirely sure yet, i'm about to take a look at source right now.
But i would think for a start, that the WebSocketSharp would have to be replaced.

What i that used for? cause it looks like you use System.Net.WebSockets for the websocket part?

**Comment by swiftyspiffy** [comment]
Ya, so the websocket class that exists in the library was used shortly but because the library using that class is not compatible with mono (as far as I and a few others could tell), we needed to resort to using WebSocketSharp.

**Comment by TheBekker** [comment]
Ahh i see, but is this still an issue in Mono?
Or would a rewrite to use the WebSocketClient instead be okay?

**Comment by swiftyspiffy** [comment]
Last I checked, mono is still broken with it. But, the websocket nuget package that TwitchLib uses is actually a build that I made (because I didn't want to flag the library as a prerelease, as the "official" version would require). I can make changes to websocketsharp for UWP compatibility, shouldn't be too much of a problem.

Here's the thread where I documented my research:
https://github.com/swiftyspiffy/TwitchLib/issues/126

**Comment by TheBekker** [comment]
I just did a quick rewrite to use the WebSocketClient instead.
Still got other issues with UWP, for example the TwitchApi class uses System.Drawing, which isn't available in UWP. Think the UWP thing to do is to use: Windows.UI.Xaml.Media.Imaging, but not 100% on that.

There is this project that might fix that: https://github.com/CoreCompat/CoreCompat
But it might now be the greates thing to start pulling in stuff like that?

I might be better of making a UWP fork of your project, if you dont want to break support on Mono?

**Comment by swiftyspiffy** [comment]
Sorry about the delay on the response. I like the idea of forking to create compatibility with UWP. If possible, I'd like to wait until we can get the TwitchApi cleaned up and supporting the important endpoints of v5. I hope to get that during break next week.

**Comment by prom3theu5** [comment]
Main issue with System.Drawing is that it uses specific features of GDI+ only available in Windows.
Because of this, I highly doubt that we will even see it included in .Net Core 2.0

I'd suggest looking into https://github.com/CoreCompat/CoreCompat as it's simply a port of the Mono version of System.Drawing

**Comment by swiftyspiffy** [comment]
So I think we can close this now that the .NET Core 2.0 branch has been merged into the master branch. Feel free to reopen/comment though :D
