### ISSUE TITLE
Pubsub err_badauth

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#164]
Now that everybody basically has access to bits I'm trying to listen for bit events in my project.

public static TwitchPubSub pubsub = new TwitchPubSub(true);
pubsub.Connect();
pubsub.OnPubSubServiceError += new EventHandler<OnPubSubServiceErrorArgs(OnPubSubServiceErrors);
Channel theChannelstuff = TwitchApi.Channels.GetChannel(channelName);
channelid = theChannelstuff.Id;
pubsub.ListenToBitsEvents(Convert.ToInt32(channelid), "oauth:keyremoved");
pubsub.OnBitsReceived += new EventHandler<OnBitsReceivedArgs>(onBitsReceived);

I noticed two issues immediately, number one there is this error being logged:

[TwitchPubSub] {"type":"RESPONSE","error":"ERR_BADAUTH","nonce":"pzYxfxOv"} 

and number two that error being logged did not fire the event OnPubSubServiceError

Is there a different way to do this than what I am doing?

**Comment by swiftyspiffy** [comment]
I can't test or really review the code all that well at the moment because I'm at school. That being said. The oauth for pubsub I think is just the token itself (and not the "oauth:" part). Additionally, the OnPubSubServiceError is an event that fires when the pubsub websockets client has an error, not when twitch returns an error. Admittedly, this is a bit confusing.

As far as an event for Twitch response to a listen request, you'll want to subscribe to the `OnListenResponse` event. The args model to this event has a Successful bool that will tell you if it was successful, as well as the nonce that was passed originally that you can use to cross reference the response.
