### ISSUE TITLE
Implement trace listeners instead of custom log function.

### ISSUE THREAD

**Issue by swiftyspiffy** [swiftyspiffy/TwitchLib#227]
Recently I've used trace listeners quite a bit in other projects and it's made me consider using them in this project. Essentially we'd have two trace listeners: one for tracing normal library flow, and one for logging specifically exceptions. Either could be turned on or off as necessary, and I think the exception one would be enabled by default.

I'm creating an issue to allow others to comment on this idea.

**Comment by Insire** [comment]
It would be good, if one could inject his own preferred method of logging, instead of having to rely on a hard coded version.

I suggest going the Dependency Injection way, and provide an Interface for logging and a default implementation, where you could log using TraceListeners, but anyone can come in and use their own prefered way of logging.

**Comment by swiftyspiffy** [comment]
This is a good idea, I think I'll run with it. I'd like to do a similar thing with the MessageThrottler in TwitchClient.

**Comment by prom3theu5** [comment]
There is a tracelogger and factory in the new logging system, which you can attach to, as well as providers for serilog, nlog and log4net, and a console logger :)

**Comment by swiftyspiffy** [comment]
As mentioned above, logging has been implemented via various supported loggers :D
