### ISSUE TITLE
GetTwitchStream fails/always returns null

### ISSUE THREAD

**Issue by bar10dr** [swiftyspiffy/TwitchLib#23]
TwitchLib.TwitchAPIClasses.TwitchStream stream = TwitchApi.GetTwitchStream("sevadus").Result;

Tried this in my own application and it always returned null.
Added TwitchApi.SetClientId(id) before the call, that makes the application hang on GetTwitchStream().

Got your example application and it hangs on GetTwitchStream() after I set the client-id as well.

**Comment by swiftyspiffy** [comment]
I was not aware of this. Will look into it now.

**Comment by swiftyspiffy** [comment]
So whatever function/method that calls GetTwitchStream needs to have the async keyword due to the call being asynchronous in nature. This means that in the example application, the button click event needs to have the async keyword.
Additionally, .Result should not exist in any of the responses to Api calls. There appears to be 4 instances of this issue. The .Result used in unison with async calls causes race conditions that lead to deadlocks, which is what I suspect is causing the nullref/fail conditions.  

After applying the fix and testing locally, I was able to pull stream data on Sevadus. I will push a fix for this shortly.

**Comment by swiftyspiffy** [comment]
Alright, give it a pull and test the example application again. The latest commit ( 7c9a81fecd7cd1e6ebf27a5f4ea9e2116037fe4b ) should have fixed your problem.

Let me know how it goes.

**Comment by bar10dr** [comment]
Worked like a charm, thank you for the quick response :)
