### ISSUE TITLE
Random Disconnects after "IndexOutOfRangeException" in Websocket.messagec

### ISSUE THREAD

**Issue by DerpyDoom** [swiftyspiffy/TwitchLib#299]
I have noticed that the TwitchClient randomly disconnects right after it throws out this error:

![twitchliberror](https://user-images.githubusercontent.com/6315513/32747920-bc12ec32-c8ba-11e7-8106-740a4872c1e3.png)

The red message says: "A connection has been closed"

I can't reproduce the error since it's happening randomly after sometime has passed.

**Comment by swiftyspiffy** [comment]
Looks like it was caused by a chat message it received. I have an idea of what it might be, but am not certain. I think the library assumes that a message has at least one character, and currently you are able to send empty messages to chat via web socket/irc, which would throw the exception you noted. Will look into it tonight

**Comment by swiftyspiffy** [comment]
@DerpyDoom So if you could try out the latest code and see if you still hit the problem, that'd be appreciated. Not a big change, but it's possible it solved it. 

Feel free to reopen this if it isn't solved.

Thanks :D
