### ISSUE TITLE
Channel Subscription Endpoints throw exceptions

### ISSUE THREAD

**Issue by D3adL0ck** [swiftyspiffy/TwitchLib#305]
Hey, I just found out that if you use the endpoint `TwitchApi.Channels.v5.CheckChannelSubscriptionByUserAsync` on a user who's not a sub, it will throw an exception saying:
> The resource you tried to access was not valid.

And when you use `TwitchApi.Channels.v5.GetAllSubscribersAsync` on a channel that's not partnered or affiliated, it will also throw an exception saying:
> The resource you requested is only available to channels that have been partnered by Twitch.

What the result should be, in my opinion, are model instances with default values.
They should also be checking if the channel is partnered/affiliated before attempting to retrieve the subscribers data to avoid the exceptions and reducing the amount of code needed when implementing those end points.

Thoughts? :)

**Comment by D3thw0lf** [comment]
Try to get the channel type first and then go trough that for example:
```c
var channel = await TwitchAPI.Channels.v5.GetChannelByIDAsync(AppSettings.LastChannelId);
                        if (channel != null && channel.BroadcasterType != "affiliate")
                        {
                          return; // or whatever Code you want here
                        }
```

**Comment by swiftyspiffy** [comment]
Are you saying that `TwitchApi.Channels.v5.CheckChannelSubscriptionByUserAsy` doesn't work on affiliates? Or that it should receive the same exception as GetAllSubscribersAsync?
Also, I think it'd be better design to have the customer check if the channel is partnered/affiliate by doing something like D3thw0lf wrote. The reason for this is that if we require every subscription-esque call require an additional call, we'd be wasting a lot of resources in the long run because I think most customers that invoke the subscriber-esque calls know that the channel they're querying is a partner/affiliate. The smaller the scope of api calls, the better in most cases I think, because it allows the customer to only call exactly what they want, without expending unnecessary web calls to the api. 

Interested in what you guys think though.

**Comment by D3thw0lf** [comment]
I agree with you. Having BroadcasterType as an enum would reduce some string-strings 👍 

@swiftyspiffy I think it's better as you already mentioned ... I don't have a Problem with checking the BroadcasterType first and I think it's better to do on my own if I need that specific check for ex. to get the Subs list. If we always check for that in every check that can check (so much check here xD) for affiliates/partner it would maybe slow down every request made.

**Comment by swiftyspiffy** [comment]
@D3adL0ck I think that'd go against the design of Twitch's API though. If you query their API and look at the response, they don't respond with an subs response. They respond with an error code. To replicate that in c#, I just throw an exception. Is there a particular reason why the exception is bad output?

**Comment by D3adL0ck** [comment]
@swiftyspiffy I just spoke with outside devs to see their opinions, the conclusion was that throwing exceptions is okay there and that the probably best replacement to that would be to simply return a null to avoid having to encapsulate the usage code with try-catch.

So I guess either way works.. so just go with what you think would be best for the lib users :)

**Comment by prom3theu5** [comment]
You don’t really have to wrap it in a try catch block

Use pattern matching and the is keyword introduced in c# 6.0 or use the Task.ContinueWith() method on the awaited task to handle exceptions

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this issue, feel free to reopen as necessary.
