### ISSUE TITLE
Support for channel with MessageThrottler.QueueSend

### ISSUE THREAD

**Issue by PinkBunneh** [swiftyspiffy/TwitchLib#330]
Hi,

I notice the method QueueSend does not accept any channel name like the Client.SendMessage do.
From the source code I see when you create a `OutgoingMessage` the channel is set this way. 
`Channel = Client.JoinedChannels.FirstOrDefault()?.Channel`

Would it be possible to add support for channel name as well?

**Comment by Syzuna** [comment]
The QueueSend isnt meant for usage from a dev. It is internally only used from the MessageThrottler to send its queued messages.

Also bcs it takes in a prepared IRC string as message where the channel is specified already due to the TwitchClient SendMessage method there is no need to change anything

**Comment by PinkBunneh** [comment]
Yea its a little confusing that QueueSend is reachable by dev 
when you are actually suppose to just use `TwitchClient.SendMessage`  and let it queue the message for you.

Thanks for the information
