### ISSUE TITLE
WebSocket VS TCP

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#343]
Hello!

I'm writing my own chat client, but using Java. I have one simple (or not? =D) question - why you use undocumented WebSocket instead of documented TCP IRC? Is there some performance, stability or some other reasons or something? Twitch doesn't offer any documentation to their WebSockets way of chat and I think they wont shut down TCP endpoint for a long time. So what's the point of using undocumented way (that can be changed in any time) over documented way (that Twitch wont change in near future)?

Thanks in advance! =)

**Comment by LuckyNoS7evin** [comment]
A websocket is only a slightly upgraded TCP connection, also websocket are designed for web browser to server communication. With this in mind and the fact Twitch use websockets as the connection within bowsers for all channel chat. I don't see them changing the system they use any time soon

**Comment by swiftyspiffy** [comment]
Hi!

So Twitch originally only allowed third party developers to interact with their IRC interface. This worked for a while but about a year ago (?) Twitch opened up web sockets for third party devs. The push has since been to move away from traditional IRC to their WebSocket interface, as far as I can tell. There are also key components that are moving (if they haven't done so already) off of IRC to websocket, like whispers.

Here are a few links:
https://discuss.dev.twitch.tv/t/websockets-and-the-future/1325/2
https://discuss.dev.twitch.tv/t/notice-of-upcoming-changes-websockets-and-secure-connections/2269

**Comment by swiftyspiffy** [comment]
Closing this, feel free to reopen if needed.
