### ISSUE TITLE
log4net exception

### ISSUE THREAD

**Issue by Legion-5** [swiftyspiffy/TwitchLib#89]
Hello, I got exception in TwitchClient constructor on this line private IrcConnection _client = new IrcConnection(); 
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in TwitchLib.dll
Additional information: Could not load file or assembly 'log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. 

After download master branch, unpack it, first build TwitchLib, then trying to debug TwitchLibExample, where I try to connect in IRC channel. This exception didn't appear before.
Thx for your project and answer.

**Comment by swiftyspiffy** [comment]
Did you get the initial exception using the NuGet package?

**Comment by Legion-5** [comment]
Yes, It seems package doesn't include in solution. Am I correct? I can't find this version of package in NuGet

**Comment by swiftyspiffy** [comment]
And this was for 1.3.3 I assume? We removed the smartirc4net reference and log4net from the library in favor of a built dlll of the project.

Try removing all NuGet referenced and then add back TwitchLib 1.3.3

**Comment by MagiusRerecros** [comment]
I removed v1.3.0 from my project and all of it's dependencies, then added TwitchLib v.1.3.3; after accounting for all of the namespace changes, I tried to run my project to make sure everything was still working, and I'm getting the same error as @Legion-5, only with SmartIRC4NET instead of Log4Net.

System.IO,FileNotFoundException; could not load file or assembly 'Meebey.SmartIrc4net, Version=0.4.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system could not find the file specified.

Exception occurs when creating a new instance of TwitchClient. Calling the constructor with only a ConnectionCredentials parameter:
`client = new TwitchClient(new ConnectionCredentials(SettingsService.Username, SettingsService.OAuth));`

**Comment by swiftyspiffy** [comment]
I think I know what the problem is. Will have a new NuGet version out in like 3 hours that should resolve the issue.

**Comment by swiftyspiffy** [comment]
For now, you may wish to just revert back to 1.3.2 in the mean time.

**Comment by swiftyspiffy** [comment]
Hey guys, sorry for the delay. Just uploaded 1.3.4. Should fix your issues. I wove log4net and smartirc4net as those were the two causing issues. As such, the library has become a bit larger, hopefully that's not a problem.

**Comment by Legion-5** [comment]
@swiftyspiffy I did not encounter this problem anymore, thx!
